name: Release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Manifest v2
        run: |
          pnpm run build:mv2
          (cd dist && zip -1 -r ../mv2.zip .)
      - name: Build Manifest v3
        run: |
          pnpm run build:mv3
          (cd dist && zip -1 -r ../mv3.zip .)
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mv2.zip
            mv3.zip
          generate_release_notes: true
